### ISSUE TITLE
Accepted People get status "Out" instead "Confirmed"

### ISSUE THREAD

**Issue by nalamar** [ahakola/LOIHCal#2]
As Topic Says

**Comment by nalamar** [comment]
**Old Invite Status:**
-- Invite Statuses
CALENDAR_INVITESTATUS_INVITED		= 1;
CALENDAR_INVITESTATUS_ACCEPTED		= 2;
CALENDAR_INVITESTATUS_DECLINED		= 3;
CALENDAR_INVITESTATUS_CONFIRMED		= 4;
CALENDAR_INVITESTATUS_OUT			= 5;
CALENDAR_INVITESTATUS_STANDBY		= 6;
CALENDAR_INVITESTATUS_SIGNEDUP		= 7;
CALENDAR_INVITESTATUS_NOT_SIGNEDUP	= 8;
CALENDAR_INVITESTATUS_TENTATIVE		= 9;
CALENDAR_MAX_INVITESTATUS			= CALENDAR_INVITESTATUS_TENTATIVE;

**New:**
1 | eventIndex | number |  
2 | status | CalendarStatus |  


0 | Invited |   |  
1 | Available |   |  
2 | Declined |   |  
3 | Confirmed |   |  
4 | Out |   |  
5 | Standby |   |  
6 | Signedup |   |  
7 | NotSignedup |   |  
8 | Tentative

Probably Solution:

C_Calendar.EventSetInviteStatus(index, 4) -- The real stuff
								inviteStatus = 4

Needs to be
C_Calendar.EventSetInviteStatus(index, 3) -- The real stuff
								inviteStatus = 3

**Comment by ahakola** [comment]
Version 9.0.0 should fix this
