### ISSUE TITLE
LOIHCal not picking up updated raider status

### ISSUE THREAD

**Issue by Poisonenvy2** [ahakola/LOIHCal#4]
When updating a raiders status on the main event screen, this is not flowing over straight away to the LOIHCal pop out screen.  I have to switch to another event and then back again, in order for the addon to register the update.

debug messages: 

Opening event (5th August):

LOIHCal: CALENDAR_OPEN_EVENT "GUILD_EVENT" 
LOIHCal: - CalendarCreateEventFrame 
LOIHCal: - Action Pending... 
LOIHCal: >getState 
LOIHCal: - Pending Action completed in 167ms. 
LOIHCal: >setState 
LOIHCal: _updateEventInfo: GUILD_EVENT 
LOIHCal: >>> 1: FATED Nathria, 2: Poisonenvy, 3: 3, 4: 8, 5: 5, 6: 2022, 7: 21, 8: 30 
LOIHCal: - 2022 8 5 2130 3-Poisonenvy 
LOIHCal: - Found DB entry 3-Poisonenvy, updating 
LOIHCal: _countSignups 
LOIHCal: <<< Healers: 1 
LOIHCal: <<< Ranged: 1 
LOIHCal: _bottomText 
LOIHCal: >>> NumInvites: 2, numSignup: 2, notReplied: 0 
LOIHCal: MIB Enabled

Amending status of a raider on that event (which updated on default UI, but not on addon):

LOIHCal: CALENDAR_UPDATE_INVITE_LIST nil false true

Switching to a different event:

LOIHCal: CALENDAR_OPEN_EVENT "GUILD_EVENT" 
LOIHCal: - CalendarCreateEventFrame 
LOIHCal: - Action Pending... 
LOIHCal: >getState 
LOIHCal: - Pending Action completed in 167ms. 
LOIHCal: >setState 
LOIHCal: _updateEventInfo: GUILD_EVENT 
LOIHCal: >>> 1: Sepulcher Normal, 2: Poisonenvy, 3: 9, 4: 7, 5: 8, 6: 2022, 7: 21, 8: 30 
LOIHCal: - 2022 7 8 2130 9-Poisonenvy 
LOIHCal: - Found DB entry 9-Poisonenvy, updating 
LOIHCal: _countSignups 
LOIHCal: <<< Tanks: 2 
LOIHCal: <<< Healers: 4 
LOIHCal: <<< Melee: 3 
LOIHCal: <<< Ranged: 6 
LOIHCal: <<< Signup: 4 
LOIHCal: _bottomText 
LOIHCal: >>> NumInvites: 19, numSignup: 16, notReplied: 1 
LOIHCal: MIB Enabled

Switching back to the previously amended event (which now shows the updated raider status):

LOIHCal: CALENDAR_OPEN_EVENT "GUILD_EVENT" 
LOIHCal: - CalendarCreateEventFrame 
LOIHCal: - Action Pending... 
LOIHCal: >getState 
LOIHCal: - Pending Action completed in 167ms. 
LOIHCal: >setState 
LOIHCal: _updateEventInfo: GUILD_EVENT 
LOIHCal: >>> 1: FATED Nathria, 2: Poisonenvy, 3: 3, 4: 8, 5: 5, 6: 2022, 7: 21, 8: 30 
LOIHCal: - 2022 8 5 2130 3-Poisonenvy 
LOIHCal: - Found DB entry 3-Poisonenvy, updating 
LOIHCal: _countSignups 
LOIHCal: <<< Healers: 1 
LOIHCal: <<< Standby: 1 
LOIHCal: _bottomText 
LOIHCal: >>> NumInvites: 2, numSignup: 1, notReplied: 0 
LOIHCal: MIB Enabled

Screenshot for example: 

![image](https://user-images.githubusercontent.com/104738891/180314167-49ebf81a-7fd9-414f-9cd5-f7dfe58b2d41.png)

**Comment by Poisonenvy2** [comment]
I've noticed that I don't need to switch to another event and then back again in order to force the update in the addon, I can simply click on the same event again in the calendar.

**Comment by ahakola** [comment]
Sorry for long wait for an answer, I was away from home.

I pushed out untagged update trying to fix this. Can you download the LOIHCal.lua (https://raw.githubusercontent.com/ahakola/LOIHCal/master/LOIHCal.lua) from this repo and replace the old one with that and test if this fixes the issue?

**Comment by Poisonenvy2** [comment]
Yes that seems to work, thank you.  :-)

**Comment by ahakola** [comment]
I'll tag this version then and close this issue. Feel free to reopen this issue if you find any related cases this fix didn't catch.
