### ISSUE TITLE
LOIHCal not loading on event open

### ISSUE THREAD

**Issue by Poisonenvy2** [ahakola/LOIHCal#5]
Error message since patch this week:

1x Interface/AddOns/LOIHCal/LOIHCalFrame.lua:241: CreateFrame(): Couldn't find inherited node "CharacterFrameTabButtonTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/LOIHCal/LOIHCalFrame.lua"]:241: in function `_tabFactory'
[string "@Interface/AddOns/LOIHCal/LOIHCalFrame.lua"]:309: in main chunk

Locals:
(*temporary) = "Button"
(*temporary) = "$parentTab1"
(*temporary) = LOIHCalTabsFrame {
 0 = <userdata>
}
(*temporary) = "CharacterFrameTabButtonTemplate"

**Comment by ahakola** [comment]
I assume this is on Retail and the new 10.0 patch? Blizzard probably removed or changed the name of the template used to create the tab-elements used in the addon. I try to find time to look into this.

**Comment by Poisonenvy2** [comment]
ah sorry, yes ;-)  Retail, patch 10.0.

**Comment by ahakola** [comment]
Version 10.0.0 should fix this.
