### ISSUE TITLE
UI Blank since 10.0.5 update

### ISSUE THREAD

**Issue by Poisonenvy2** [ahakola/LOIHCal#6]
Just updated today, and my UI is blank.

Bugsack picked up:

2x LOIHCal/LOIHCal.lua:605: field 'day' missing in date table
[string "=[C]"]: in function `time'
[string "@LOIHCal/LOIHCal.lua"]:605: in function <LOIHCal/LOIHCal.lua:477>
[string "@LOIHCal/LOIHCal.lua"]:1679: in function `tabSelectedCallback'
[string "@SharedXML/TabSystem/TabSystemTemplates.lua"]:175: in function `SetTab'
[string "@LOIHCal/LOIHCal.lua"]:1960: in function `?'
[string "@LOIHCal/LOIHCal.lua"]:1743: in function <LOIHCal/LOIHCal.lua:1742>

Locals:
(*temporary) = <table> {
 monthDay = 20
 weekday = 2
 month = 2
 minute = 8
 hour = 20
 year = 2023
}
(*temporary) = nil

![image](https://user-images.githubusercontent.com/104738891/220580226-462d9ada-2fcd-4093-bf66-f49dce2fbdcd.png)

**Comment by ahakola** [comment]
I'll look into this asap

**Comment by ahakola** [comment]
Pushed out version 10.0.5.1 and it should fix this issue or at least it shouldn't error out anymore if it runs into the same problem. Let me know how it goes.

**Comment by Poisonenvy2** [comment]
Yes that fixed it .. thank you ;-)
