### ISSUE TITLE
UI is empty

### ISSUE THREAD

**Issue by Poisonenvy2** [ahakola/LOIHCal#7]
Just updated to the latest version .. and suddenly my addon is empty.  Got bug:

![image](https://user-images.githubusercontent.com/104738891/236003905-e3beb5cb-752f-4470-8101-a907fa30c596.png)

7x SharedXML/SecureScrollTemplates.lua:191: attempt to index local 'scrollBar' (a nil value)
[string "@SharedXML/SecureScrollTemplates.lua"]:191: in function `FauxScrollFrame_Update'
[string "@LOIHCal/LOIHCal.lua"]:1229: in function `updateScrollBar'
[string "@LOIHCal/LOIHCalFrame.lua"]:238: in function <LOIHCal/LOIHCalFrame.lua:237>
[string "=[C]"]: in function `Show'
[string "@LOIHCal/LOIHCal.lua"]:1689: in function `tabSelectedCallback'
[string "@SharedXML/TabSystem/TabSystemTemplates.lua"]:175: in function `SetTab'
[string "@LOIHCal/LOIHCal.lua"]:1973: in function `?'
[string "@LOIHCal/LOIHCal.lua"]:1756: in function <LOIHCal/LOIHCal.lua:1755>

Locals:
frame = TanksScrollBar {
 0 = <userdata>
 ScrollBar = Frame {
 }
}
numItems = 0
numToDisplay = 6
buttonHeight = 15
button = nil
smallWidth = nil
bigWidth = nil
highlightFrame = nil
smallHighlightWidth = nil
bigHighlightWidth = nil
alwaysShowScrollBar = nil
scrollBar = nil
scrollChildFrame = nil
scrollUpButton = nil
scrollDownButton = nil
showScrollBar = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "TanksScrollBarScrollBarScrollDownButton"
(*temporary) = "ScrollBarScrollDownButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'scrollBar' (a nil value)"

**Comment by ahakola** [comment]
Thanks for reporting, I'll look into this.

**Comment by ahakola** [comment]
Pushed out commit a578be96d42ddb16e95185d2347bb6a80cd1aa53 and tagged it with version 10.1.0.1 that should fix this issue.

Scrolling feels bit different because the new scrollbar moves in smaller steps than the old one and it doesn't always hit the threshold to snap to show next/previous name in the list. I might come back to look this more when I have time, but at least this should be in usable state now.
