### ISSUE TITLE
Pre-Patch Error

### ISSUE THREAD

**Issue by Poisonenvy2** [ahakola/LOIHCal#8]
2x LOIHCal/LOIHCal.lua:2149: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@LOIHCal/LOIHCal.lua"]:2149: in main chunk

Locals:
ADDON_NAME = "LOIHCal"
ns = <table> {
 version = "10.2.7"
 colors = <table> {
 }
 functions = <table> {
 }
 rolesList = <table> {
 }
 difficulties = <table> {
 }
 numSignup = 0
 DBdefaults = <table> {
 }
 openEvent = <table> {
 }
 inviteTable = <table> {
 }
 selectedPlayer = false
 selected = false
 L = <table> {
 }
 notReplied = 0
 role = <table> {
 }
}
L = <table> {
 AutoRolesDesc = "Automaticly give accepted/confirmed players roles. Given roles are based on previous roles."
 AutoRoles = "Auto-Roles"
 AutomationSettingsTitle = "Automation settings"
 AutoConfirmDesc = "Automaticly Confirm players with role. Confirmed players cannot change their sign up status later while accepted players can."
 QuickMode = "Quick mode"
 SaveDesc = "Save whisper message."
 ResetWhisper = "Reset to Default"
 Placeholder = "Use %s in the whisper for event name placeholder."
 Out = "Out"
 Roles = "Roles"
 DefaultInvWhisper = "Raid event "%s" is about to start, please accept this invite."
 Cancel = "Cancel"
 Standbys = "Standbys"
 TimeEstimate = "Estimated time left: ~%ds"
 Healers = "Healers"
 ServerWait = "Waiting for server-side data..."
 Role = "Role: %s"
 Dec = "Dec"
 DefaultSettingsTitle = "Default settings for new raid events"
 Tanks = "Tanks"
 Melee = "Melee"
 RoleDesc = "Change player role to %s"
 Sta = "Sta"
 DPS = "DPS"
 RaidDifficulty = "Raid Difficulty"
 AttachModeDesc = "Do you want to attach your %s frame on top or on side of the Default view?"
 AutoConfirm = "Auto-Confirm"
 DefaultViewDesc = "Open straight to %s view instead of Default view when opening event"
 Ten = "Ten"
 Con = "Con"
 SkinWithDesc = "Do you want to skin %s with %s?"
 RemoveDesc = "%sShift+Click%s to remove player from Auto-Role-list.
Player will be re-listed if you open any events where the player has been given a role."
 SignupDesc = "^%sName%s / +%sName%s
Event moderator
%s@%sName%s@%s
No role data for auto-roles"
 AutoRoleDecay = "Auto-Roles decay"
 QuickModeDesc = "In quick mode, instead of selecting groups by clicking the group title, you use your mouse LeftButton/RightButton with modifiers None/Shift/Ctrl to determine where clicked player is sent.

Shift:
Left = Tanks - Right = Healers
None:
Left = Melee - Right = Ranged
Ctrl:
Left = Signups - Right = Standbys"
 SendWhispersDesc = "Do you want to inform players with whisper on Mass Invite?"
 ResetDB = "Reset DB"
 WhisperSettingsTitle = "Whisper settings"
 NotReplied = "Not replied"
 SendingInvites = "Sending invites..."
 AttachMode = "Attach on top of the Default view"
 ResetDBDesc = "%sShift+Click%s to Reset DB"
 CMD_LIST = "/loihcal ( %s | %s )"
 Save = "Save"
 DefaultView = "Open %s view as Default"
 SkinReloadDesc = "You have to reload your UI to remove ElvUI skinning.
Pressing this button will reload your UI."
 SkinReload = "Reload UI"
 Remove = "Remove"
 SkinWith = "Skin with %s"
 SkinningTitle = "Skinning settings"
 ResetWhisperDesc = "Reset whisper message back to Default."
 MassInvite = "Mass Invite"
 AutoRoleDecayDesc = "Automaticly remove players from Roles-list if they haven't signed up for %i months or more."
 AutoStandBy = "Auto-Stand By"
 MassInviteDesc = "Start Mass Invite"
 AutoStandByDesc = "Automaticly move signed up players to Stand By when the selected raid size has been filled."
 Not = "Not"
 SendWhispers = "Send Whispers"
 Default = "Default"
 Sig = "Sig"
 ReloadWarning = "%sWarning:%s Pressing this button will reload your UI, delete all event- and role-data and restore Default settings."
 RemovedFromEvent = "|cffff0000Removed|r character "|c%1$s%2$s|r" from event "%3$s" (%4$02d.%5$02d.%6$04d %7$02d:%8$02d)"
 Inv = "Inv"
 Signups = "Signups"
 Ranged = "Ranged"
 LastSeen = "Last signup: %s"
 Acc = "Acc"
 GeneralSettingsTitle = "General settings"
 CMD_CONFIG = "config"
 CMD_RESET = "reset"
}
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonSt

**Comment by ahakola** [comment]
Is it safe to assume this is in TWW pre-patch or beta (11.0.x) instead of 10.2.7?

Edit: Note to self, remember to read the title of the issue before asking questions!

**Comment by Poisonenvy2** [comment]
Haha sorry .. I was a little vague .. I couldn't remember the patch number!  Yeah it's TWW pre-patch that launched this week in retail.

**Comment by ahakola** [comment]
11.0 PTR is down, so I can't test this yet, but if you see this before the PTR comes back up and I have time to test this myself, could you replace your LOIHCal.lua with https://github.com/ahakola/LOIHCal/blob/11.0/LOIHCal.lua and see if it gets you past this error. If not, let me know and if you get further, let me know all the new errors you run into.

**Comment by Poisonenvy2** [comment]
I've tested this and it seems to work.  Can't see any problems and no errors are popping up.  Thank you!!

**Comment by ahakola** [comment]
Glad it works. I'll close this one, but don't hesitate to reopen/open a new ticket if you run into other issues.
